<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.acme</groupId>
        <artifactId>secret-extension-integration-tests-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>secret-extension-integration-tests-vault</artifactId>
    <name>Secret Extension - Integration Tests Vault</name>

    <dependencies>
        <dependency>
            <groupId>io.quarkiverse.vault</groupId>
            <artifactId>quarkus-vault</artifactId>
            <version>${quarkus-vault.version}</version>
        </dependency>
    </dependencies>
</project>
